# Static marketing site. The pages are generated by `go run ./build` and
# committed, so this image needs no toolchain: it copies files and serves them.
#
# Generating at build time would mean carrying Go and the generator into the
# image for a result that is byte identical to what is already in the tree.

FROM nginx:1.27-alpine

COPY default.conf /etc/nginx/conf.d/default.conf

# Pages, plus the files written for crawlers and answer engines.
COPY *.html /usr/share/nginx/html/
COPY robots.txt sitemap.xml llms.txt llms-full.txt /usr/share/nginx/html/

# Styles, behaviour, icon sprite, self-hosted fonts and link preview cards.
COPY assets/ /usr/share/nginx/html/assets/

EXPOSE 80
